sudo: false
language: node_js

node_js:
    - '8'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm install

script:
  - npm run lint
  - npm run codecov
  - npm run build

after_script:
  - cd ./build
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Travis Build Bot Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages