sudo: false
language: node_js

node_js:
    - '8'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - yarn lint
  - yarn codecov
  - yarn deploy:travis
